rest_product:
    resource: '@AppBundle/Controller/Rest/ProductController.php'
    type: rest
    prefix: product

rest_cart:
    resource: '@AppBundle/Controller/Rest/CartController.php'
    type: rest
    prefix: cart

NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc
