# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

#services:
#    product.subscriber.product_serializer:
#        class: AppBundle\Subscriber\ProductSerializerSubscriber
#        arguments:
#            - '@session'
#        tags:
#            - { name: jms_serializer.event_subscriber }
